server:
        port: 8763
spring:
  application:
    name: eurekaclient
  rabbitmq:
        host: 192.168.137.2
        port: 5672
        username: admin
        password: 123456
  sleuth:
    sampler:
      percentage: 1.0
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,bus-refresh
